spring:
  profiles:
    active: dev
  application:
    name: service-edu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8001
mybatis-plus:
  global-config:
      db-config:
          logic-not-delete-value: 0
          logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/atguigu/edu/mapper/*.xml

    #spring:
     # application:
     #   name: service-edu
    #profiles:
       # active: dev
    ####  application-dev.yml
    #server:
    #  port: 8001

    #mybatis-plus:
     #configuration:
     #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
     #mapper-locations: classpath:com/atguigu/service/*/mapper/*.xml

     #global-config:
     #   db-config:
      #    logic-delete-value: 1
      #    logic-not-delete-value: 0

    #spring:
     # datasource:
     #    type: com.zaxxer.hikari.HikariDataSource
     #    driver-class-name: com.mysql.cj.jdbc.Driver
      #   url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
     #    username: root
      #   password: root
      #hikari:
       #   connection-test-query: SELECT 1
       #  connection-timeout: 60000
      #   idle-timeout: 500000
       #  max-lifetime: 540000
      #   maximum-pool-size: 12
       #  minimum-idle: 10
       #  pool-name: GuliHikariPool
    #jackson:
      #  date-format: yyyy-MM-dd HH:mm:ss
      #  time-zone: GMT+8