server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
    oss:
      file:
        endpoint: oss-cn-beijing.aliyuncs.com
        keyid: LTAI4GHrzFyU8MedqvTxyBH7
        keysecret : 6GEMMAEZ6DQrfv2gkhAxf2WNkus4wx
        bucketname : edu-0904


